import type { DiagramResult } from "@/lib/contracts";

export const demoResult: DiagramResult = {
  id: "offline-demo-centrifugal-pump",
  image: {
    src: "/demo-pump.svg",
    mimeType: "image/svg+xml",
    width: 1440,
    height: 960,
    revisedPrompt: null,
  },
  annotation: {
    title: "Centrifugal pump anatomy",
    summary:
      "A generated cutaway paired with an independent, editable spatial annotation layer.",
    parts: [
      {
        id: "casing",
        index: 0,
        name: "Casing",
        description:
          "Encloses the impeller and forms the volute that converts fluid velocity into pressure.",
        visible: true,
        anchor: { x: 0.34, y: 0.29 },
        box: { x: 0.19, y: 0.23, width: 0.46, height: 0.58 },
        confidence: 0.97,
        evidence: "The orange cut shell forms a continuous boundary around the blue pump chamber.",
        reviewStatus: "ai-draft",
      },
      {
        id: "impeller",
        index: 1,
        name: "Impeller",
        description:
          "Rotates with the shaft and transfers mechanical energy to the fluid through curved vanes.",
        visible: true,
        anchor: { x: 0.424, y: 0.558 },
        box: { x: 0.313, y: 0.389, width: 0.222, height: 0.326 },
        confidence: 0.99,
        evidence: "A blue rotating assembly with six orange vanes is visible at the chamber center.",
        reviewStatus: "ai-draft",
      },
      {
        id: "shaft",
        index: 2,
        name: "Shaft",
        description: "Transfers drive torque to the impeller while maintaining its axis of rotation.",
        visible: true,
        anchor: { x: 0.73, y: 0.558 },
        box: { x: 0.42, y: 0.527, width: 0.47, height: 0.063 },
        confidence: 0.96,
        evidence: "A horizontal metal shaft extends from the impeller center into the drive assembly.",
        reviewStatus: "ai-draft",
      },
      {
        id: "seal",
        index: 3,
        name: "Mechanical seal",
        description: "Restricts fluid leakage where the rotating shaft exits the pump casing.",
        visible: true,
        anchor: { x: 0.605, y: 0.545 },
        box: { x: 0.568, y: 0.447, width: 0.071, height: 0.219 },
        confidence: 0.91,
        evidence: "A narrow orange ring assembly surrounds the shaft at the casing exit.",
        reviewStatus: "ai-draft",
      },
      {
        id: "inlet",
        index: 4,
        name: "Inlet",
        description: "Guides fluid axially into the low-pressure center of the impeller.",
        visible: true,
        anchor: { x: 0.112, y: 0.531 },
        box: { x: 0.03, y: 0.414, width: 0.222, height: 0.235 },
        confidence: 0.98,
        evidence: "The left horizontal flanged port aligns with the center of the impeller.",
        reviewStatus: "ai-draft",
      },
      {
        id: "outlet",
        index: 5,
        name: "Outlet",
        description: "Directs pressurized fluid from the casing into the discharge pipework.",
        visible: true,
        anchor: { x: 0.432, y: 0.128 },
        box: { x: 0.348, y: 0.047, width: 0.166, height: 0.278 },
        confidence: 0.98,
        evidence: "A vertical flanged port rises from the top of the casing.",
        reviewStatus: "ai-draft",
      },
      {
        id: "bearing",
        index: 6,
        name: "Bearing",
        description: "Supports the shaft, limits radial movement, and reduces rotational friction.",
        visible: true,
        anchor: { x: 0.765, y: 0.558 },
        box: { x: 0.716, y: 0.444, width: 0.101, height: 0.226 },
        confidence: 0.9,
        evidence: "A concentric orange ring surrounds the shaft inside the right bearing housing.",
        reviewStatus: "ai-draft",
      },
    ],
    warnings: [
      "This is a curated offline asset, not a live Azure model output.",
      "Spatial locations are an AI draft and require expert review for engineering use.",
    ],
  },
  provenance: {
    source: "offline-demo",
    imageModel: "deterministic-svg-demo",
    visionModel: "curated-demo-annotations",
    generatedAt: "2026-07-31T00:00:00.000Z",
    reviewRequired: true,
  },
};
