import type { DiagramResult } from "@/lib/contracts";

export const demoResult: DiagramResult = {
  id: "offline-demo-centrifugal-pump",
  image: {
    src: "/demo-pump.svg",
    mimeType: "image/svg+xml",
    width: 1440,
    height: 960,
    revisedPrompt: null,
  },
  annotation: {
    title: "离心泵剖视与空间语义层",
    summary:
      "基础图像不含标签；编号、引线、坐标、说明和复核状态均来自独立的可编辑标注层。",
    parts: [
      {
        id: "casing",
        index: 0,
        name: "泵壳",
        description:
          "包围叶轮并形成蜗形流道，将液体的部分速度能转化为压力能。",
        visible: true,
        anchor: { x: 0.34, y: 0.29 },
        box: { x: 0.19, y: 0.23, width: 0.46, height: 0.58 },
        confidence: 0.97,
        evidence: "橙色剖切外壳围绕蓝色泵腔，轮廓连续且边界清晰。",
        reviewStatus: "ai-draft",
      },
      {
        id: "impeller",
        index: 1,
        name: "叶轮",
        description:
          "随主轴旋转，通过弯曲叶片向液体传递机械能。",
        visible: true,
        anchor: { x: 0.424, y: 0.558 },
        box: { x: 0.313, y: 0.389, width: 0.222, height: 0.326 },
        confidence: 0.99,
        evidence: "泵腔中央可见带六个橙色叶片的蓝色旋转件。",
        reviewStatus: "ai-draft",
      },
      {
        id: "shaft",
        index: 2,
        name: "主轴",
        description: "把驱动端的扭矩传递给叶轮，并保持旋转中心。",
        visible: true,
        anchor: { x: 0.73, y: 0.558 },
        box: { x: 0.42, y: 0.527, width: 0.47, height: 0.063 },
        confidence: 0.96,
        evidence: "水平金属圆轴从叶轮中心延伸至右侧驱动组件。",
        reviewStatus: "ai-draft",
      },
      {
        id: "seal",
        index: 3,
        name: "机械密封",
        description: "限制液体沿旋转主轴向泵体外泄漏。",
        visible: true,
        anchor: { x: 0.605, y: 0.545 },
        box: { x: 0.568, y: 0.447, width: 0.071, height: 0.219 },
        confidence: 0.91,
        evidence: "泵壳出口处围绕主轴的橙色窄环组件。",
        reviewStatus: "ai-draft",
      },
      {
        id: "inlet",
        index: 4,
        name: "进水口",
        description: "沿叶轮轴向把液体引入叶轮中央的低压区域。",
        visible: true,
        anchor: { x: 0.112, y: 0.531 },
        box: { x: 0.03, y: 0.414, width: 0.222, height: 0.235 },
        confidence: 0.98,
        evidence: "图左侧与叶轮中心同轴的水平法兰管口。",
        reviewStatus: "ai-draft",
      },
      {
        id: "outlet",
        index: 5,
        name: "出水口",
        description: "将泵壳内增压后的液体导向外部管路。",
        visible: true,
        anchor: { x: 0.432, y: 0.128 },
        box: { x: 0.348, y: 0.047, width: 0.166, height: 0.278 },
        confidence: 0.98,
        evidence: "泵壳顶部向上延伸的带法兰垂直管口。",
        reviewStatus: "ai-draft",
      },
      {
        id: "bearing",
        index: 6,
        name: "轴承",
        description: "支撑主轴、控制径向位移并降低旋转摩擦。",
        visible: true,
        anchor: { x: 0.765, y: 0.558 },
        box: { x: 0.716, y: 0.444, width: 0.101, height: 0.226 },
        confidence: 0.9,
        evidence: "右侧轴承座内可见包围主轴的同心橙色环件。",
        reviewStatus: "ai-draft",
      },
    ],
    warnings: [
      "这是离线演示资产，不是 Azure 模型的真实输出。",
      "定位结果属于 AI 草稿；工程用途需要专业人员逐项确认。",
    ],
  },
  provenance: {
    source: "offline-demo",
    imageModel: "deterministic-svg-demo",
    visionModel: "curated-demo-annotations",
    generatedAt: "2026-07-31T00:00:00.000Z",
    reviewRequired: true,
  },
};
