"use client";

/* eslint-disable @next/next/no-img-element */

import { BookOpenCheck, Check, Copy, FolderPlus, Globe2, Lock, Pencil, Plus, Share2, Trash2, X } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

import { CustomSelect } from "@/components/custom-select";
import { FavoriteButton } from "@/components/favorite-button";
import type { DiagramResult } from "@/lib/contracts";

export function FigureDetail({ result, owner, isPublic, collections, favorited, signedIn }: { result: DiagramResult; owner: boolean; isPublic: boolean; collections: { id: string; name: string }[]; favorited: boolean; signedIn: boolean }) {
  const router = useRouter(); const [selectedPart, setSelectedPart] = useState(result.annotation.parts[0]?.id || ""); const [collection, setCollection] = useState(collections[0]?.id || ""); const [saved, setSaved] = useState(false); const [publishing, setPublishing] = useState(false); const [deleting, setDeleting] = useState(false);
  const [editingTitle, setEditingTitle] = useState(false); const [titleDraft, setTitleDraft] = useState(result.annotation.title); const [renaming, setRenaming] = useState(false); const [shared, setShared] = useState(false); const [duplicating, setDuplicating] = useState(false);
  const active = result.annotation.parts.find((part) => part.id === selectedPart);
  async function save() { if (!collection) return; const response = await fetch(`/api/collections/${collection}/figures`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ figureId: result.id }) }); if (response.ok) setSaved(true); }
  async function togglePublic() { setPublishing(true); await fetch(`/api/figures/${result.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ isPublic: !isPublic }) }); router.refresh(); setPublishing(false); }
  async function remove() { if (deleting) return; if (!window.confirm("Delete this figure permanently? This also removes it from any collections and clears its quiz history.")) return; setDeleting(true); const response = await fetch(`/api/figures/${result.id}`, { method: "DELETE" }); if (response.ok) { router.push("/library"); router.refresh(); } else { setDeleting(false); window.alert("Could not delete this figure. Please try again."); } }
  function startRename() { setTitleDraft(result.annotation.title); setEditingTitle(true); }
  async function share() { const url = `${window.location.origin}/figures/${result.id}`; try { await navigator.clipboard.writeText(url); setShared(true); window.setTimeout(() => setShared(false), 2200); } catch { window.prompt("Copy this figure link:", url); } }
  async function duplicate() { if (duplicating) return; setDuplicating(true); const response = await fetch(`/api/figures/${result.id}/duplicate`, { method: "POST" }); if (response.ok) { const body = await response.json() as { id: string }; router.push(`/figures/${body.id}`); router.refresh(); } else { setDuplicating(false); window.alert("Could not save a copy of this figure."); } }
  async function saveTitle() { const trimmed = titleDraft.trim(); if (!trimmed || trimmed === result.annotation.title) { setEditingTitle(false); return; } setRenaming(true); const response = await fetch(`/api/figures/${result.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: trimmed }) }); setRenaming(false); if (response.ok) { setEditingTitle(false); router.refresh(); } else { window.alert("Could not rename this figure."); } }
  return <>
    <header className="figure-detail-head"><div><p>{result.provenance.imageModel} · {new Date(result.provenance.generatedAt).toLocaleDateString()}</p>{owner && editingTitle ? <div className="figure-title-edit"><input value={titleDraft} maxLength={160} autoFocus onChange={(event) => setTitleDraft(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void saveTitle(); if (event.key === "Escape") setEditingTitle(false); }} /><button type="button" aria-label="Save title" onClick={() => void saveTitle()} disabled={renaming}><Check size={16} /></button><button type="button" aria-label="Cancel" onClick={() => setEditingTitle(false)}><X size={16} /></button></div> : <h1>{result.annotation.title}{owner && <button type="button" className="figure-title-rename" aria-label="Rename figure" onClick={startRename}><Pencil size={16} /></button>}</h1>}<span>{result.annotation.summary}</span></div><div>{owner && <button onClick={() => void togglePublic()} disabled={publishing}>{isPublic ? <Globe2 /> : <Lock />}{isPublic ? "Public" : "Private"}</button>}{owner && <button className="figure-delete-button" onClick={() => void remove()} disabled={deleting}><Trash2 size={16} />{deleting ? "Deleting…" : "Delete"}</button>}{signedIn && <FavoriteButton figureId={result.id} initialFavorited={favorited} variant="detail" />}{signedIn && !owner && <button type="button" onClick={() => void duplicate()} disabled={duplicating}><Copy size={16} />{duplicating ? "Saving…" : "Save a copy"}</button>}<button type="button" onClick={() => void share()} title={owner && !isPublic ? "Link works once you make this figure public" : "Copy a link to this figure"}>{shared ? <Check /> : <Share2 />}{shared ? "Copied" : "Share"}</button><Link href={`/quiz?figure=${result.id}`}><BookOpenCheck />Take the quiz</Link></div></header>
    <div className="figure-detail-grid"><section className="figure-detail-canvas"><img src={result.image.src} alt={result.annotation.title} />{result.annotation.parts.filter((part) => part.visible).map((part) => <button type="button" key={part.id} aria-label={part.name} aria-pressed={part.id === selectedPart} data-active={part.id === selectedPart} onClick={() => setSelectedPart(part.id)} style={{ left: `${part.anchor.x * 100}%`, top: `${part.anchor.y * 100}%` }}>{part.index + 1}</button>)}</section><aside className="figure-detail-aside"><p>COMPONENT MAP</p><h2>{result.annotation.parts.length} things to notice</h2><nav>{result.annotation.parts.map((part) => <button key={part.id} aria-pressed={part.id === selectedPart} data-active={part.id === selectedPart} onClick={() => setSelectedPart(part.id)}><span>{String(part.index + 1).padStart(2, "0")}</span><strong>{part.name}</strong><small>{Math.round(part.confidence * 100)}%</small></button>)}</nav>{active && <article><p>SELECTED COMPONENT</p><h3>{active.name}</h3><span>{active.description}</span><small>{active.evidence}</small></article>}</aside></div>
    {collections.length > 0 ? <section className="save-bar"><FolderPlus /><div><strong>Add this figure to a collection</strong><span>Keep connected ideas together.</span></div><CustomSelect compact label="Collection" value={collection} onChange={(value) => { setCollection(value); setSaved(false); }} options={collections.map((item) => ({ value: item.id, label: item.name }))} /><button onClick={() => void save()} disabled={saved}>{saved ? <Check /> : <Plus />}{saved ? "Saved" : "Add"}</button></section> : <section className="save-bar"><FolderPlus /><div><strong>Start a collection</strong><span>Group this figure with connected ideas.</span></div><Link href="/collections">Create collection</Link></section>}
  </>;
}
